package com.medgenome.auth.dto;

import java.util.List;

/**
 * Token details extracted from JWT token.
 * This matches the token structure generated by the IAM service.
 */
public record TokenDetails(
        String username,           // sub claim - user email
        Integer tenantId,            // tenant_id claim - can be String or Integer
        String role,                // role claim - active role name
        List<String> permissions,   // permissions claim - list of permissions
        String sessionId,          // sessionId claim - session identifier
        Integer tenant,              // tenant claim - tenant identifier
        String sid                  // sid claim - session identifier (alternative)
) {
}